# Generated by Django 5.1.6 on 2025-03-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
