# Generated by Django 5.1.5 on 2025-02-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
